// +build !ignore_autogenerated

/*
  Copyright 2017 The Kubernetes Authors.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/
// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	car "api-server/pkg/apis/car"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_CarController_To_car_CarController,
		Convert_car_CarController_To_v1alpha1_CarController,
		Convert_v1alpha1_CarControllerList_To_car_CarControllerList,
		Convert_car_CarControllerList_To_v1alpha1_CarControllerList,
		Convert_v1alpha1_CarControllerSpec_To_car_CarControllerSpec,
		Convert_car_CarControllerSpec_To_v1alpha1_CarControllerSpec,
		Convert_v1alpha1_CarControllerStatus_To_car_CarControllerStatus,
		Convert_car_CarControllerStatus_To_v1alpha1_CarControllerStatus,
		Convert_v1alpha1_CarControllerStatusStrategy_To_car_CarControllerStatusStrategy,
		Convert_car_CarControllerStatusStrategy_To_v1alpha1_CarControllerStatusStrategy,
		Convert_v1alpha1_CarControllerStrategy_To_car_CarControllerStrategy,
		Convert_car_CarControllerStrategy_To_v1alpha1_CarControllerStrategy,
	)
}

func autoConvert_v1alpha1_CarController_To_car_CarController(in *CarController, out *car.CarController, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_CarControllerSpec_To_car_CarControllerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CarControllerStatus_To_car_CarControllerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CarController_To_car_CarController is an autogenerated conversion function.
func Convert_v1alpha1_CarController_To_car_CarController(in *CarController, out *car.CarController, s conversion.Scope) error {
	return autoConvert_v1alpha1_CarController_To_car_CarController(in, out, s)
}

func autoConvert_car_CarController_To_v1alpha1_CarController(in *car.CarController, out *CarController, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_car_CarControllerSpec_To_v1alpha1_CarControllerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_car_CarControllerStatus_To_v1alpha1_CarControllerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_car_CarController_To_v1alpha1_CarController is an autogenerated conversion function.
func Convert_car_CarController_To_v1alpha1_CarController(in *car.CarController, out *CarController, s conversion.Scope) error {
	return autoConvert_car_CarController_To_v1alpha1_CarController(in, out, s)
}

func autoConvert_v1alpha1_CarControllerList_To_car_CarControllerList(in *CarControllerList, out *car.CarControllerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]car.CarController)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_CarControllerList_To_car_CarControllerList is an autogenerated conversion function.
func Convert_v1alpha1_CarControllerList_To_car_CarControllerList(in *CarControllerList, out *car.CarControllerList, s conversion.Scope) error {
	return autoConvert_v1alpha1_CarControllerList_To_car_CarControllerList(in, out, s)
}

func autoConvert_car_CarControllerList_To_v1alpha1_CarControllerList(in *car.CarControllerList, out *CarControllerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]CarController)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_car_CarControllerList_To_v1alpha1_CarControllerList is an autogenerated conversion function.
func Convert_car_CarControllerList_To_v1alpha1_CarControllerList(in *car.CarControllerList, out *CarControllerList, s conversion.Scope) error {
	return autoConvert_car_CarControllerList_To_v1alpha1_CarControllerList(in, out, s)
}

func autoConvert_v1alpha1_CarControllerSpec_To_car_CarControllerSpec(in *CarControllerSpec, out *car.CarControllerSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_CarControllerSpec_To_car_CarControllerSpec is an autogenerated conversion function.
func Convert_v1alpha1_CarControllerSpec_To_car_CarControllerSpec(in *CarControllerSpec, out *car.CarControllerSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CarControllerSpec_To_car_CarControllerSpec(in, out, s)
}

func autoConvert_car_CarControllerSpec_To_v1alpha1_CarControllerSpec(in *car.CarControllerSpec, out *CarControllerSpec, s conversion.Scope) error {
	return nil
}

// Convert_car_CarControllerSpec_To_v1alpha1_CarControllerSpec is an autogenerated conversion function.
func Convert_car_CarControllerSpec_To_v1alpha1_CarControllerSpec(in *car.CarControllerSpec, out *CarControllerSpec, s conversion.Scope) error {
	return autoConvert_car_CarControllerSpec_To_v1alpha1_CarControllerSpec(in, out, s)
}

func autoConvert_v1alpha1_CarControllerStatus_To_car_CarControllerStatus(in *CarControllerStatus, out *car.CarControllerStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_CarControllerStatus_To_car_CarControllerStatus is an autogenerated conversion function.
func Convert_v1alpha1_CarControllerStatus_To_car_CarControllerStatus(in *CarControllerStatus, out *car.CarControllerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CarControllerStatus_To_car_CarControllerStatus(in, out, s)
}

func autoConvert_car_CarControllerStatus_To_v1alpha1_CarControllerStatus(in *car.CarControllerStatus, out *CarControllerStatus, s conversion.Scope) error {
	return nil
}

// Convert_car_CarControllerStatus_To_v1alpha1_CarControllerStatus is an autogenerated conversion function.
func Convert_car_CarControllerStatus_To_v1alpha1_CarControllerStatus(in *car.CarControllerStatus, out *CarControllerStatus, s conversion.Scope) error {
	return autoConvert_car_CarControllerStatus_To_v1alpha1_CarControllerStatus(in, out, s)
}

func autoConvert_v1alpha1_CarControllerStatusStrategy_To_car_CarControllerStatusStrategy(in *CarControllerStatusStrategy, out *car.CarControllerStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_CarControllerStatusStrategy_To_car_CarControllerStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_CarControllerStatusStrategy_To_car_CarControllerStatusStrategy(in *CarControllerStatusStrategy, out *car.CarControllerStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_CarControllerStatusStrategy_To_car_CarControllerStatusStrategy(in, out, s)
}

func autoConvert_car_CarControllerStatusStrategy_To_v1alpha1_CarControllerStatusStrategy(in *car.CarControllerStatusStrategy, out *CarControllerStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_car_CarControllerStatusStrategy_To_v1alpha1_CarControllerStatusStrategy is an autogenerated conversion function.
func Convert_car_CarControllerStatusStrategy_To_v1alpha1_CarControllerStatusStrategy(in *car.CarControllerStatusStrategy, out *CarControllerStatusStrategy, s conversion.Scope) error {
	return autoConvert_car_CarControllerStatusStrategy_To_v1alpha1_CarControllerStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_CarControllerStrategy_To_car_CarControllerStrategy(in *CarControllerStrategy, out *car.CarControllerStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_CarControllerStrategy_To_car_CarControllerStrategy is an autogenerated conversion function.
func Convert_v1alpha1_CarControllerStrategy_To_car_CarControllerStrategy(in *CarControllerStrategy, out *car.CarControllerStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_CarControllerStrategy_To_car_CarControllerStrategy(in, out, s)
}

func autoConvert_car_CarControllerStrategy_To_v1alpha1_CarControllerStrategy(in *car.CarControllerStrategy, out *CarControllerStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_car_CarControllerStrategy_To_v1alpha1_CarControllerStrategy is an autogenerated conversion function.
func Convert_car_CarControllerStrategy_To_v1alpha1_CarControllerStrategy(in *car.CarControllerStrategy, out *CarControllerStrategy, s conversion.Scope) error {
	return autoConvert_car_CarControllerStrategy_To_v1alpha1_CarControllerStrategy(in, out, s)
}
