/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package car

import (
	"fmt"
	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	"k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/endpoints/request"
	"k8s.io/apiserver/pkg/registry/rest"
)

var (
	InternalCarController = builders.NewInternalResource(
		"carcontrollers",
		"CarController",
		func() runtime.Object { return &CarController{} },
		func() runtime.Object { return &CarControllerList{} },
	)
	InternalCarControllerStatus = builders.NewInternalResourceStatus(
		"carcontrollers",
		"CarControllerStatus",
		func() runtime.Object { return &CarController{} },
		func() runtime.Object { return &CarControllerList{} },
	)
	// Registered resources and subresources
	ApiVersion = builders.NewApiGroup("car.emruz.example.com").WithKinds(
		InternalCarController,
		InternalCarControllerStatus,
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +genclient
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type CarController struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   CarControllerSpec
	Status CarControllerStatus
}

type CarControllerSpec struct {
}

type CarControllerStatus struct {
}

//
// CarController Functions and Structs
//
// +k8s:deepcopy-gen=false
type CarControllerStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type CarControllerStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type CarControllerList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []CarController
}

func (CarController) NewStatus() interface{} {
	return CarControllerStatus{}
}

func (pc *CarController) GetStatus() interface{} {
	return pc.Status
}

func (pc *CarController) SetStatus(s interface{}) {
	pc.Status = s.(CarControllerStatus)
}

func (pc *CarController) GetSpec() interface{} {
	return pc.Spec
}

func (pc *CarController) SetSpec(s interface{}) {
	pc.Spec = s.(CarControllerSpec)
}

func (pc *CarController) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *CarController) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc CarController) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store CarController.
// +k8s:deepcopy-gen=false
type CarControllerRegistry interface {
	ListCarControllers(ctx request.Context, options *internalversion.ListOptions) (*CarControllerList, error)
	GetCarController(ctx request.Context, id string, options *metav1.GetOptions) (*CarController, error)
	CreateCarController(ctx request.Context, id *CarController) (*CarController, error)
	UpdateCarController(ctx request.Context, id *CarController) (*CarController, error)
	DeleteCarController(ctx request.Context, id string) (bool, error)
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewCarControllerRegistry(sp builders.StandardStorageProvider) CarControllerRegistry {
	return &storageCarController{sp}
}

// Implement Registry
// storage puts strong typing around storage calls
// +k8s:deepcopy-gen=false
type storageCarController struct {
	builders.StandardStorageProvider
}

func (s *storageCarController) ListCarControllers(ctx request.Context, options *internalversion.ListOptions) (*CarControllerList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	st := s.GetStandardStorage()
	obj, err := st.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*CarControllerList), err
}

func (s *storageCarController) GetCarController(ctx request.Context, id string, options *metav1.GetOptions) (*CarController, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*CarController), nil
}

func (s *storageCarController) CreateCarController(ctx request.Context, object *CarController) (*CarController, error) {
	st := s.GetStandardStorage()
	obj, err := st.Create(ctx, object, nil, true)
	if err != nil {
		return nil, err
	}
	return obj.(*CarController), nil
}

func (s *storageCarController) UpdateCarController(ctx request.Context, object *CarController) (*CarController, error) {
	st := s.GetStandardStorage()
	obj, _, err := st.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object), nil, nil)
	if err != nil {
		return nil, err
	}
	return obj.(*CarController), nil
}

func (s *storageCarController) DeleteCarController(ctx request.Context, id string) (bool, error) {
	st := s.GetStandardStorage()
	_, sync, err := st.Delete(ctx, id, nil)
	return sync, err
}
