// +build !ignore_autogenerated

/*
  Copyright 2017 The Kubernetes Authors.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/
// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	customdp "api-server/pkg/apis/customdp"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_CustomDeployment_To_customdp_CustomDeployment,
		Convert_customdp_CustomDeployment_To_v1alpha1_CustomDeployment,
		Convert_v1alpha1_CustomDeploymentList_To_customdp_CustomDeploymentList,
		Convert_customdp_CustomDeploymentList_To_v1alpha1_CustomDeploymentList,
		Convert_v1alpha1_CustomDeploymentSpec_To_customdp_CustomDeploymentSpec,
		Convert_customdp_CustomDeploymentSpec_To_v1alpha1_CustomDeploymentSpec,
		Convert_v1alpha1_CustomDeploymentStatus_To_customdp_CustomDeploymentStatus,
		Convert_customdp_CustomDeploymentStatus_To_v1alpha1_CustomDeploymentStatus,
		Convert_v1alpha1_CustomDeploymentStatusStrategy_To_customdp_CustomDeploymentStatusStrategy,
		Convert_customdp_CustomDeploymentStatusStrategy_To_v1alpha1_CustomDeploymentStatusStrategy,
		Convert_v1alpha1_CustomDeploymentStrategy_To_customdp_CustomDeploymentStrategy,
		Convert_customdp_CustomDeploymentStrategy_To_v1alpha1_CustomDeploymentStrategy,
	)
}

func autoConvert_v1alpha1_CustomDeployment_To_customdp_CustomDeployment(in *CustomDeployment, out *customdp.CustomDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_CustomDeploymentSpec_To_customdp_CustomDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CustomDeploymentStatus_To_customdp_CustomDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CustomDeployment_To_customdp_CustomDeployment is an autogenerated conversion function.
func Convert_v1alpha1_CustomDeployment_To_customdp_CustomDeployment(in *CustomDeployment, out *customdp.CustomDeployment, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomDeployment_To_customdp_CustomDeployment(in, out, s)
}

func autoConvert_customdp_CustomDeployment_To_v1alpha1_CustomDeployment(in *customdp.CustomDeployment, out *CustomDeployment, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_customdp_CustomDeploymentSpec_To_v1alpha1_CustomDeploymentSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_customdp_CustomDeploymentStatus_To_v1alpha1_CustomDeploymentStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_customdp_CustomDeployment_To_v1alpha1_CustomDeployment is an autogenerated conversion function.
func Convert_customdp_CustomDeployment_To_v1alpha1_CustomDeployment(in *customdp.CustomDeployment, out *CustomDeployment, s conversion.Scope) error {
	return autoConvert_customdp_CustomDeployment_To_v1alpha1_CustomDeployment(in, out, s)
}

func autoConvert_v1alpha1_CustomDeploymentList_To_customdp_CustomDeploymentList(in *CustomDeploymentList, out *customdp.CustomDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]customdp.CustomDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_CustomDeploymentList_To_customdp_CustomDeploymentList is an autogenerated conversion function.
func Convert_v1alpha1_CustomDeploymentList_To_customdp_CustomDeploymentList(in *CustomDeploymentList, out *customdp.CustomDeploymentList, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomDeploymentList_To_customdp_CustomDeploymentList(in, out, s)
}

func autoConvert_customdp_CustomDeploymentList_To_v1alpha1_CustomDeploymentList(in *customdp.CustomDeploymentList, out *CustomDeploymentList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]CustomDeployment)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_customdp_CustomDeploymentList_To_v1alpha1_CustomDeploymentList is an autogenerated conversion function.
func Convert_customdp_CustomDeploymentList_To_v1alpha1_CustomDeploymentList(in *customdp.CustomDeploymentList, out *CustomDeploymentList, s conversion.Scope) error {
	return autoConvert_customdp_CustomDeploymentList_To_v1alpha1_CustomDeploymentList(in, out, s)
}

func autoConvert_v1alpha1_CustomDeploymentSpec_To_customdp_CustomDeploymentSpec(in *CustomDeploymentSpec, out *customdp.CustomDeploymentSpec, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_CustomDeploymentSpec_To_customdp_CustomDeploymentSpec is an autogenerated conversion function.
func Convert_v1alpha1_CustomDeploymentSpec_To_customdp_CustomDeploymentSpec(in *CustomDeploymentSpec, out *customdp.CustomDeploymentSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomDeploymentSpec_To_customdp_CustomDeploymentSpec(in, out, s)
}

func autoConvert_customdp_CustomDeploymentSpec_To_v1alpha1_CustomDeploymentSpec(in *customdp.CustomDeploymentSpec, out *CustomDeploymentSpec, s conversion.Scope) error {
	return nil
}

// Convert_customdp_CustomDeploymentSpec_To_v1alpha1_CustomDeploymentSpec is an autogenerated conversion function.
func Convert_customdp_CustomDeploymentSpec_To_v1alpha1_CustomDeploymentSpec(in *customdp.CustomDeploymentSpec, out *CustomDeploymentSpec, s conversion.Scope) error {
	return autoConvert_customdp_CustomDeploymentSpec_To_v1alpha1_CustomDeploymentSpec(in, out, s)
}

func autoConvert_v1alpha1_CustomDeploymentStatus_To_customdp_CustomDeploymentStatus(in *CustomDeploymentStatus, out *customdp.CustomDeploymentStatus, s conversion.Scope) error {
	return nil
}

// Convert_v1alpha1_CustomDeploymentStatus_To_customdp_CustomDeploymentStatus is an autogenerated conversion function.
func Convert_v1alpha1_CustomDeploymentStatus_To_customdp_CustomDeploymentStatus(in *CustomDeploymentStatus, out *customdp.CustomDeploymentStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomDeploymentStatus_To_customdp_CustomDeploymentStatus(in, out, s)
}

func autoConvert_customdp_CustomDeploymentStatus_To_v1alpha1_CustomDeploymentStatus(in *customdp.CustomDeploymentStatus, out *CustomDeploymentStatus, s conversion.Scope) error {
	return nil
}

// Convert_customdp_CustomDeploymentStatus_To_v1alpha1_CustomDeploymentStatus is an autogenerated conversion function.
func Convert_customdp_CustomDeploymentStatus_To_v1alpha1_CustomDeploymentStatus(in *customdp.CustomDeploymentStatus, out *CustomDeploymentStatus, s conversion.Scope) error {
	return autoConvert_customdp_CustomDeploymentStatus_To_v1alpha1_CustomDeploymentStatus(in, out, s)
}

func autoConvert_v1alpha1_CustomDeploymentStatusStrategy_To_customdp_CustomDeploymentStatusStrategy(in *CustomDeploymentStatusStrategy, out *customdp.CustomDeploymentStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_CustomDeploymentStatusStrategy_To_customdp_CustomDeploymentStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_CustomDeploymentStatusStrategy_To_customdp_CustomDeploymentStatusStrategy(in *CustomDeploymentStatusStrategy, out *customdp.CustomDeploymentStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomDeploymentStatusStrategy_To_customdp_CustomDeploymentStatusStrategy(in, out, s)
}

func autoConvert_customdp_CustomDeploymentStatusStrategy_To_v1alpha1_CustomDeploymentStatusStrategy(in *customdp.CustomDeploymentStatusStrategy, out *CustomDeploymentStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_customdp_CustomDeploymentStatusStrategy_To_v1alpha1_CustomDeploymentStatusStrategy is an autogenerated conversion function.
func Convert_customdp_CustomDeploymentStatusStrategy_To_v1alpha1_CustomDeploymentStatusStrategy(in *customdp.CustomDeploymentStatusStrategy, out *CustomDeploymentStatusStrategy, s conversion.Scope) error {
	return autoConvert_customdp_CustomDeploymentStatusStrategy_To_v1alpha1_CustomDeploymentStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_CustomDeploymentStrategy_To_customdp_CustomDeploymentStrategy(in *CustomDeploymentStrategy, out *customdp.CustomDeploymentStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_CustomDeploymentStrategy_To_customdp_CustomDeploymentStrategy is an autogenerated conversion function.
func Convert_v1alpha1_CustomDeploymentStrategy_To_customdp_CustomDeploymentStrategy(in *CustomDeploymentStrategy, out *customdp.CustomDeploymentStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomDeploymentStrategy_To_customdp_CustomDeploymentStrategy(in, out, s)
}

func autoConvert_customdp_CustomDeploymentStrategy_To_v1alpha1_CustomDeploymentStrategy(in *customdp.CustomDeploymentStrategy, out *CustomDeploymentStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_customdp_CustomDeploymentStrategy_To_v1alpha1_CustomDeploymentStrategy is an autogenerated conversion function.
func Convert_customdp_CustomDeploymentStrategy_To_v1alpha1_CustomDeploymentStrategy(in *customdp.CustomDeploymentStrategy, out *CustomDeploymentStrategy, s conversion.Scope) error {
	return autoConvert_customdp_CustomDeploymentStrategy_To_v1alpha1_CustomDeploymentStrategy(in, out, s)
}
