// +build !ignore_autogenerated

/*
  Copyright 2017 The Kubernetes Authors.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
*/
// This file was autogenerated by conversion-gen. Do not edit it manually!

package v1alpha1

import (
	customrc "api-server/pkg/apis/customrc"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
	unsafe "unsafe"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(scheme *runtime.Scheme) error {
	return scheme.AddGeneratedConversionFuncs(
		Convert_v1alpha1_CustomReplicationController_To_customrc_CustomReplicationController,
		Convert_customrc_CustomReplicationController_To_v1alpha1_CustomReplicationController,
		Convert_v1alpha1_CustomReplicationControllerList_To_customrc_CustomReplicationControllerList,
		Convert_customrc_CustomReplicationControllerList_To_v1alpha1_CustomReplicationControllerList,
		Convert_v1alpha1_CustomReplicationControllerSpec_To_customrc_CustomReplicationControllerSpec,
		Convert_customrc_CustomReplicationControllerSpec_To_v1alpha1_CustomReplicationControllerSpec,
		Convert_v1alpha1_CustomReplicationControllerStatus_To_customrc_CustomReplicationControllerStatus,
		Convert_customrc_CustomReplicationControllerStatus_To_v1alpha1_CustomReplicationControllerStatus,
		Convert_v1alpha1_CustomReplicationControllerStatusStrategy_To_customrc_CustomReplicationControllerStatusStrategy,
		Convert_customrc_CustomReplicationControllerStatusStrategy_To_v1alpha1_CustomReplicationControllerStatusStrategy,
		Convert_v1alpha1_CustomReplicationControllerStrategy_To_customrc_CustomReplicationControllerStrategy,
		Convert_customrc_CustomReplicationControllerStrategy_To_v1alpha1_CustomReplicationControllerStrategy,
	)
}

func autoConvert_v1alpha1_CustomReplicationController_To_customrc_CustomReplicationController(in *CustomReplicationController, out *customrc.CustomReplicationController, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_v1alpha1_CustomReplicationControllerSpec_To_customrc_CustomReplicationControllerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_v1alpha1_CustomReplicationControllerStatus_To_customrc_CustomReplicationControllerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_CustomReplicationController_To_customrc_CustomReplicationController is an autogenerated conversion function.
func Convert_v1alpha1_CustomReplicationController_To_customrc_CustomReplicationController(in *CustomReplicationController, out *customrc.CustomReplicationController, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomReplicationController_To_customrc_CustomReplicationController(in, out, s)
}

func autoConvert_customrc_CustomReplicationController_To_v1alpha1_CustomReplicationController(in *customrc.CustomReplicationController, out *CustomReplicationController, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	if err := Convert_customrc_CustomReplicationControllerSpec_To_v1alpha1_CustomReplicationControllerSpec(&in.Spec, &out.Spec, s); err != nil {
		return err
	}
	if err := Convert_customrc_CustomReplicationControllerStatus_To_v1alpha1_CustomReplicationControllerStatus(&in.Status, &out.Status, s); err != nil {
		return err
	}
	return nil
}

// Convert_customrc_CustomReplicationController_To_v1alpha1_CustomReplicationController is an autogenerated conversion function.
func Convert_customrc_CustomReplicationController_To_v1alpha1_CustomReplicationController(in *customrc.CustomReplicationController, out *CustomReplicationController, s conversion.Scope) error {
	return autoConvert_customrc_CustomReplicationController_To_v1alpha1_CustomReplicationController(in, out, s)
}

func autoConvert_v1alpha1_CustomReplicationControllerList_To_customrc_CustomReplicationControllerList(in *CustomReplicationControllerList, out *customrc.CustomReplicationControllerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]customrc.CustomReplicationController)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_CustomReplicationControllerList_To_customrc_CustomReplicationControllerList is an autogenerated conversion function.
func Convert_v1alpha1_CustomReplicationControllerList_To_customrc_CustomReplicationControllerList(in *CustomReplicationControllerList, out *customrc.CustomReplicationControllerList, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomReplicationControllerList_To_customrc_CustomReplicationControllerList(in, out, s)
}

func autoConvert_customrc_CustomReplicationControllerList_To_v1alpha1_CustomReplicationControllerList(in *customrc.CustomReplicationControllerList, out *CustomReplicationControllerList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]CustomReplicationController)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_customrc_CustomReplicationControllerList_To_v1alpha1_CustomReplicationControllerList is an autogenerated conversion function.
func Convert_customrc_CustomReplicationControllerList_To_v1alpha1_CustomReplicationControllerList(in *customrc.CustomReplicationControllerList, out *CustomReplicationControllerList, s conversion.Scope) error {
	return autoConvert_customrc_CustomReplicationControllerList_To_v1alpha1_CustomReplicationControllerList(in, out, s)
}

func autoConvert_v1alpha1_CustomReplicationControllerSpec_To_customrc_CustomReplicationControllerSpec(in *CustomReplicationControllerSpec, out *customrc.CustomReplicationControllerSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Template = in.Template
	return nil
}

// Convert_v1alpha1_CustomReplicationControllerSpec_To_customrc_CustomReplicationControllerSpec is an autogenerated conversion function.
func Convert_v1alpha1_CustomReplicationControllerSpec_To_customrc_CustomReplicationControllerSpec(in *CustomReplicationControllerSpec, out *customrc.CustomReplicationControllerSpec, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomReplicationControllerSpec_To_customrc_CustomReplicationControllerSpec(in, out, s)
}

func autoConvert_customrc_CustomReplicationControllerSpec_To_v1alpha1_CustomReplicationControllerSpec(in *customrc.CustomReplicationControllerSpec, out *CustomReplicationControllerSpec, s conversion.Scope) error {
	out.Replicas = in.Replicas
	out.Template = in.Template
	return nil
}

// Convert_customrc_CustomReplicationControllerSpec_To_v1alpha1_CustomReplicationControllerSpec is an autogenerated conversion function.
func Convert_customrc_CustomReplicationControllerSpec_To_v1alpha1_CustomReplicationControllerSpec(in *customrc.CustomReplicationControllerSpec, out *CustomReplicationControllerSpec, s conversion.Scope) error {
	return autoConvert_customrc_CustomReplicationControllerSpec_To_v1alpha1_CustomReplicationControllerSpec(in, out, s)
}

func autoConvert_v1alpha1_CustomReplicationControllerStatus_To_customrc_CustomReplicationControllerStatus(in *CustomReplicationControllerStatus, out *customrc.CustomReplicationControllerStatus, s conversion.Scope) error {
	out.AvailableReplicas = in.AvailableReplicas
	out.CreatingReplicas = in.CreatingReplicas
	out.TerminatingReplicas = in.TerminatingReplicas
	return nil
}

// Convert_v1alpha1_CustomReplicationControllerStatus_To_customrc_CustomReplicationControllerStatus is an autogenerated conversion function.
func Convert_v1alpha1_CustomReplicationControllerStatus_To_customrc_CustomReplicationControllerStatus(in *CustomReplicationControllerStatus, out *customrc.CustomReplicationControllerStatus, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomReplicationControllerStatus_To_customrc_CustomReplicationControllerStatus(in, out, s)
}

func autoConvert_customrc_CustomReplicationControllerStatus_To_v1alpha1_CustomReplicationControllerStatus(in *customrc.CustomReplicationControllerStatus, out *CustomReplicationControllerStatus, s conversion.Scope) error {
	out.AvailableReplicas = in.AvailableReplicas
	out.CreatingReplicas = in.CreatingReplicas
	out.TerminatingReplicas = in.TerminatingReplicas
	return nil
}

// Convert_customrc_CustomReplicationControllerStatus_To_v1alpha1_CustomReplicationControllerStatus is an autogenerated conversion function.
func Convert_customrc_CustomReplicationControllerStatus_To_v1alpha1_CustomReplicationControllerStatus(in *customrc.CustomReplicationControllerStatus, out *CustomReplicationControllerStatus, s conversion.Scope) error {
	return autoConvert_customrc_CustomReplicationControllerStatus_To_v1alpha1_CustomReplicationControllerStatus(in, out, s)
}

func autoConvert_v1alpha1_CustomReplicationControllerStatusStrategy_To_customrc_CustomReplicationControllerStatusStrategy(in *CustomReplicationControllerStatusStrategy, out *customrc.CustomReplicationControllerStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_v1alpha1_CustomReplicationControllerStatusStrategy_To_customrc_CustomReplicationControllerStatusStrategy is an autogenerated conversion function.
func Convert_v1alpha1_CustomReplicationControllerStatusStrategy_To_customrc_CustomReplicationControllerStatusStrategy(in *CustomReplicationControllerStatusStrategy, out *customrc.CustomReplicationControllerStatusStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomReplicationControllerStatusStrategy_To_customrc_CustomReplicationControllerStatusStrategy(in, out, s)
}

func autoConvert_customrc_CustomReplicationControllerStatusStrategy_To_v1alpha1_CustomReplicationControllerStatusStrategy(in *customrc.CustomReplicationControllerStatusStrategy, out *CustomReplicationControllerStatusStrategy, s conversion.Scope) error {
	out.DefaultStatusStorageStrategy = in.DefaultStatusStorageStrategy
	return nil
}

// Convert_customrc_CustomReplicationControllerStatusStrategy_To_v1alpha1_CustomReplicationControllerStatusStrategy is an autogenerated conversion function.
func Convert_customrc_CustomReplicationControllerStatusStrategy_To_v1alpha1_CustomReplicationControllerStatusStrategy(in *customrc.CustomReplicationControllerStatusStrategy, out *CustomReplicationControllerStatusStrategy, s conversion.Scope) error {
	return autoConvert_customrc_CustomReplicationControllerStatusStrategy_To_v1alpha1_CustomReplicationControllerStatusStrategy(in, out, s)
}

func autoConvert_v1alpha1_CustomReplicationControllerStrategy_To_customrc_CustomReplicationControllerStrategy(in *CustomReplicationControllerStrategy, out *customrc.CustomReplicationControllerStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_v1alpha1_CustomReplicationControllerStrategy_To_customrc_CustomReplicationControllerStrategy is an autogenerated conversion function.
func Convert_v1alpha1_CustomReplicationControllerStrategy_To_customrc_CustomReplicationControllerStrategy(in *CustomReplicationControllerStrategy, out *customrc.CustomReplicationControllerStrategy, s conversion.Scope) error {
	return autoConvert_v1alpha1_CustomReplicationControllerStrategy_To_customrc_CustomReplicationControllerStrategy(in, out, s)
}

func autoConvert_customrc_CustomReplicationControllerStrategy_To_v1alpha1_CustomReplicationControllerStrategy(in *customrc.CustomReplicationControllerStrategy, out *CustomReplicationControllerStrategy, s conversion.Scope) error {
	out.DefaultStorageStrategy = in.DefaultStorageStrategy
	return nil
}

// Convert_customrc_CustomReplicationControllerStrategy_To_v1alpha1_CustomReplicationControllerStrategy is an autogenerated conversion function.
func Convert_customrc_CustomReplicationControllerStrategy_To_v1alpha1_CustomReplicationControllerStrategy(in *customrc.CustomReplicationControllerStrategy, out *CustomReplicationControllerStrategy, s conversion.Scope) error {
	return autoConvert_customrc_CustomReplicationControllerStrategy_To_v1alpha1_CustomReplicationControllerStrategy(in, out, s)
}
