
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1alpha1.car.emruz.example.com
  labels:
    api: carservice
    apiserver: "true"
spec:
  version: v1alpha1
  group: car.emruz.example.com
  groupPriorityMinimum: 2000
  priority: 200
  service:
    name: carservice
    namespace: default
  versionPriority: 10
  caBundle: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURwekNDQW8rZ0F3SUJBZ0lKQUppdnBGZDVjQnJKTUEwR0NTcUdTSWIzRFFFQkN3VUFNR294Q3pBSkJnTlYKQkFZVEFuVnVNUXN3Q1FZRFZRUUlEQUp6ZERFS01BZ0dBMVVFQnd3QmJERUtNQWdHQTFVRUNnd0JiekVMTUFrRwpBMVVFQ3d3Q2IzVXhLVEFuQmdOVkJBTU1JR05oY25ObGNuWnBZMlV0WTJWeWRHbG1hV05oZEdVdFlYVjBhRzl5CmFYUjVNQjRYRFRFNE1ESXhOakE0TVRrME5Wb1hEVEU1TURJeE5qQTRNVGswTlZvd2FqRUxNQWtHQTFVRUJoTUMKZFc0eEN6QUpCZ05WQkFnTUFuTjBNUW93Q0FZRFZRUUhEQUZzTVFvd0NBWURWUVFLREFGdk1Rc3dDUVlEVlFRTApEQUp2ZFRFcE1DY0dBMVVFQXd3Z1kyRnljMlZ5ZG1salpTMWpaWEowYVdacFkyRjBaUzFoZFhSb2IzSnBkSGt3CmdnRWlNQTBHQ1NxR1NJYjNEUUVCQVFVQUE0SUJEd0F3Z2dFS0FvSUJBUURDSllVcEtNbjBYSTlnQ1RlSUhQVHUKdFJ4NU9HTVZQc2VkTGd2L2cxVUN6L1J0bFV6amJJTi93OG9FdEJueE5DMzJId1RFR3FlZm5Rb2RzdFkrWjIycQpKMzN6VWFZQlRZWUVSbDVuVTZ2dkZUNjBjZ2s3M3B3YkxrcFI4bFF1WTBLc3pVdWVHKzViMG5KVFpVSHJjTDgvCkZFYmtHTVhkRUNicWI2MDVOQ2I1cTM5bmJEczJYek5sMnNRTk1kTHY4ZjJZZmlFakowb0xvU0IydWEyUGlMWkwKeWpJL2RnakE4UEltTXc5eEZsbWlmaDN1VXhsdVRsNzJ0SWh5RjBsU2ozOHFTU0dUMy9GMDMyRVVIdmlEb0JCOApTNk9JaDJ1S05qZExBNG9pZlRaY1VPK2tNUWk3dGZoVXduUVNMWWdJOE1JMWlwWGtVUllDa1k3ajhKNUlzK09GCkFnTUJBQUdqVURCT01CMEdBMVVkRGdRV0JCUUdCdzFtMlIzcUh2R25lbDFEUk5KZ2JHeG5jekFmQmdOVkhTTUUKR0RBV2dCUUdCdzFtMlIzcUh2R25lbDFEUk5KZ2JHeG5jekFNQmdOVkhSTUVCVEFEQVFIL01BMEdDU3FHU0liMwpEUUVCQ3dVQUE0SUJBUUNtVTJPazFEVnpXMXJCN2dUdHhyZUxZdy9GRWhabEY4VjZFWjJQai9oYlJOVlJiRnFrCjVCWnNlcEYwYlpVM1VEUjhZUmxVWDBNMUYzL1RPNDhuSEtQU0NUcFdwN05Bay8wRmZnN1NKMnhua3FqenJCcm4KcEVadG9UOGloNlFZMFFZZE1STHM1SDFXRmRKMVZHdURCd1ZNeTZoc240N1FUMWZtZlNVSHV4TVROQXQrZTVqeAoxL2VINFBpZHFObWJQaFdVNnpNTDRFN3ZFNWVXMXJnY2d1TnhGclpkZHNvekNWOGNKNWwyaU93cXYvS0tSVDBlCkd3bFU3ZGpHUE4rQXhTVUFjc09aYUtETVhHTGRwTzFIQUd1SXozZkVQT2YycHB5aElEQzBNeGYvRG85bzB3czUKVWJIVGNHYldnalFtdmVHbXVvcmM5U3I0SnpLYkZFb2ltQi9KCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K"
---
apiVersion: v1
kind: Service
metadata:
  name: carservice
  namespace: default
  labels:
    api: carservice
    apiserver: "true"
spec:
  type: ExternalName
  externalName: "10.0.2.2"
  ports:
  - port: 443
    protocol: TCP
