/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package customdp

import (
	"fmt"
	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	"k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/endpoints/request"
	"k8s.io/apiserver/pkg/registry/rest"
)

var (
	InternalCustomDeployment = builders.NewInternalResource(
		"customdeployments",
		"CustomDeployment",
		func() runtime.Object { return &CustomDeployment{} },
		func() runtime.Object { return &CustomDeploymentList{} },
	)
	InternalCustomDeploymentStatus = builders.NewInternalResourceStatus(
		"customdeployments",
		"CustomDeploymentStatus",
		func() runtime.Object { return &CustomDeployment{} },
		func() runtime.Object { return &CustomDeploymentList{} },
	)
	// Registered resources and subresources
	ApiVersion = builders.NewApiGroup("customdp.emruz.com").WithKinds(
		InternalCustomDeployment,
		InternalCustomDeploymentStatus,
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +genclient
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type CustomDeployment struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   CustomDeploymentSpec
	Status CustomDeploymentStatus
}

type CustomDeploymentSpec struct {
}

type CustomDeploymentStatus struct {
}

//
// CustomDeployment Functions and Structs
//
// +k8s:deepcopy-gen=false
type CustomDeploymentStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type CustomDeploymentStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type CustomDeploymentList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []CustomDeployment
}

func (CustomDeployment) NewStatus() interface{} {
	return CustomDeploymentStatus{}
}

func (pc *CustomDeployment) GetStatus() interface{} {
	return pc.Status
}

func (pc *CustomDeployment) SetStatus(s interface{}) {
	pc.Status = s.(CustomDeploymentStatus)
}

func (pc *CustomDeployment) GetSpec() interface{} {
	return pc.Spec
}

func (pc *CustomDeployment) SetSpec(s interface{}) {
	pc.Spec = s.(CustomDeploymentSpec)
}

func (pc *CustomDeployment) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *CustomDeployment) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc CustomDeployment) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store CustomDeployment.
// +k8s:deepcopy-gen=false
type CustomDeploymentRegistry interface {
	ListCustomDeployments(ctx request.Context, options *internalversion.ListOptions) (*CustomDeploymentList, error)
	GetCustomDeployment(ctx request.Context, id string, options *metav1.GetOptions) (*CustomDeployment, error)
	CreateCustomDeployment(ctx request.Context, id *CustomDeployment) (*CustomDeployment, error)
	UpdateCustomDeployment(ctx request.Context, id *CustomDeployment) (*CustomDeployment, error)
	DeleteCustomDeployment(ctx request.Context, id string) (bool, error)
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewCustomDeploymentRegistry(sp builders.StandardStorageProvider) CustomDeploymentRegistry {
	return &storageCustomDeployment{sp}
}

// Implement Registry
// storage puts strong typing around storage calls
// +k8s:deepcopy-gen=false
type storageCustomDeployment struct {
	builders.StandardStorageProvider
}

func (s *storageCustomDeployment) ListCustomDeployments(ctx request.Context, options *internalversion.ListOptions) (*CustomDeploymentList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	st := s.GetStandardStorage()
	obj, err := st.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*CustomDeploymentList), err
}

func (s *storageCustomDeployment) GetCustomDeployment(ctx request.Context, id string, options *metav1.GetOptions) (*CustomDeployment, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*CustomDeployment), nil
}

func (s *storageCustomDeployment) CreateCustomDeployment(ctx request.Context, object *CustomDeployment) (*CustomDeployment, error) {
	st := s.GetStandardStorage()
	obj, err := st.Create(ctx, object, nil, true)
	if err != nil {
		return nil, err
	}
	return obj.(*CustomDeployment), nil
}

func (s *storageCustomDeployment) UpdateCustomDeployment(ctx request.Context, object *CustomDeployment) (*CustomDeployment, error) {
	st := s.GetStandardStorage()
	obj, _, err := st.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object), nil, nil)
	if err != nil {
		return nil, err
	}
	return obj.(*CustomDeployment), nil
}

func (s *storageCustomDeployment) DeleteCustomDeployment(ctx request.Context, id string) (bool, error) {
	st := s.GetStandardStorage()
	_, sync, err := st.Delete(ctx, id, nil)
	return sync, err
}
